#!/usr/local/bin/python3

import argparse
import io
import re
import sys
import os
import subprocess

argumentParser = argparse.ArgumentParser()

argumentParser.add_argument("-v", "--version",
                            help="Print version information and quit immediately. All other options and arguments will be ignored.",
                            action="store_const",
                            const=True)
argumentParser.add_argument("-r", "--root",
                            help="Become root after logging in.",
                            action="store_const",
                            const=True)
argumentParser.add_argument("-l", "--list",
                            help="Print the contents of the server's index file. The site argument will be ignored.",
                            action="store_const",
                            const=True)

argumentParser.add_argument("server",
                            help="The name of a server bookmark in your SSH configuration file.",
                            action="store",
                            nargs='?',
                            default="null")
argumentParser.add_argument("site",
                            help="The name of a site bookmark in the server's index file.",
                            nargs='?',
                            default="null")

arguments = argumentParser.parse_args()

if arguments.version == True:
  print("Client version 0.4 by Daniel Flaum (daniel.flaum@sprydigital.com)")
  sys.exit()

if arguments.server == "null":
    print("Error: No server bookmark was provided.")
    exit(1)

ssh_config_file = open(os.path.expanduser("~/.ssh/config"))
ssh_config_contents = ssh_config_file.read()
ssh_config_lines = ssh_config_contents.splitlines()

server_bookmark_is_present = False
for line in ssh_config_lines:
  match = re.match("Host " + re.escape(arguments.server), line)
  if match:
    server_bookmark_is_present = True

if server_bookmark_is_present == False:
  print("Error: The server bookmark you specified does not exist in your SSH configuration file.")
  print("     : I search through " + os.path.expanduser("~/.ssh/config"))
  sys.exit(1)

environment_variables = "SSSH_SITE=\"" + arguments.site + "\" "

if arguments.list == True:
  environment_variables = environment_variables + "SSSH_LIST=1 "
else:
  if arguments.site == "null":
    print("Error: No site bookmark was provided.")
    exit(1)

if arguments.root == True:
  environment_variables = environment_variables + "SSSH_BECOME_ROOT=1 "

command = "ssh -t " + arguments.server + " \"" + environment_variables + "sudo -sE /bin/bash --init-file /usr/bin/ssshrouter\""

subprocess.run(command, shell=True)